# One-shot generator for crates/wqxemu/src/keypad/font.rs.
# Rasterizes the label character set from system CJK fonts into
# anti-aliased alpha bitmaps that are embedded as static data so the
# code skin can print the real device labels without any image asset.
# Run once from the repository root:  python tools/genfont.py
from PIL import Image, ImageDraw, ImageFont
from pathlib import Path

LABEL_FONT = r"C:\Windows\Fonts\msyh.ttc"
BRAND_FONT = r"C:\Windows\Fonts\simhei.ttf"
BRAND = "文曲星"

STRINGS = [
    "文曲星", "真人发音", "插入", "删除", "查找", "修改", "查设", "同反义",
    "变化", "辨析", "例句", "汉英", "通讯", "换算", "资料", "游戏", "其他",
    "记事", "测验", "英汉", "名片", "计算", "提醒", "时间", "行程", "网络",
    "发音", "报时", "输入", "求助", "中英数", "中英度", "输入法", "跳出",
    "符号", "空格", "继续", "报文", "事件", "闹钟", "变焦", "反查", "录音",
    "剑桥", "根查字", "解析", "词库", "学习", "系统", "帮助", "零点", "翻页",
    "查看", "翻译", "双解", "英解", "汉解", "税", "合",
]
LABEL_SIZES = [12, 14, 16]
BRAND_SIZES = [22, 34, 40, 48]
LATIN_SIZES = [10, 12, 14, 16, 20, 24, 28]

latin = "".join(chr(c) for c in range(0x20, 0x7F)) + "·®"
cjk = "".join(sorted(set("".join(STRINGS)) - set(latin)))

jobs = []
for size in LATIN_SIZES:
    jobs += [(ch, size, LABEL_FONT) for ch in latin]
for size in LABEL_SIZES:
    jobs += [(ch, size, LABEL_FONT) for ch in cjk]
for size in BRAND_SIZES:
    jobs += [(ch, size, BRAND_FONT) for ch in BRAND]

jobs.sort(key=lambda job: (ord(job[0]), job[1]))

def rasterize(ch, size, font_file):
    font = ImageFont.truetype(font_file, size)
    box = font.getbbox(ch, anchor="ls")
    width, height = box[2] - box[0], box[3] - box[1]
    if width <= 0 or height <= 0:
        return None
    canvas = Image.new("L", (width + 2, height + 2), 0)
    ImageDraw.Draw(canvas).text((1 - box[0], 1 - box[1]), ch, font=font, fill=255, anchor="ls")
    canvas = canvas.crop((1, 1, 1 + width, 1 + height))
    alpha = list(canvas.getdata())
    if not any(alpha):
        return None
    return width, height, box[0], box[1], round(font.getlength(ch)), alpha

rows = ["// Generated by tools/genfont.py — anti-aliased label glyphs embedded as",
        "// static data so the code skin can print the real device labels without",
        "// any image asset. Each entry: (character, pixel size, metrics, alpha).",
        "",
        "pub(super) struct Glyph {",
        "    pub(super) width: usize,",
        "    pub(super) height: usize,",
        "    pub(super) x_offset: i32,",
        "    pub(super) y_offset: i32,",
        "    pub(super) advance: i32,",
        "    pub(super) alpha: &'static [u8],",
        "}",
        "",
        "const GLYPHS: &[(u32, u8, Glyph)] = &["]

total = 0
kept = 0
for ch, size, font_file in jobs:
    made = rasterize(ch, size, font_file)
    if made is None:
        continue
    width, height, x_off, y_off, advance, alpha = made
    total += len(alpha)
    kept += 1
    hexes = ",".join(f"0x{a:02X}" for a in alpha)
    rows.append(f"    (0x{ord(ch):04X}, {size}, Glyph {{ width: {width}, height: {height}, "
                f"x_offset: {x_off}, y_offset: {y_off}, advance: {advance}, "
                f"alpha: &[{hexes}] }}),")

rows += ["];", "",
         "pub(super) fn glyph(ch: char, size: u8) -> Option<&'static Glyph> {",
         "    let key = (ch as u32, size);",
         "    GLYPHS",
         "        .binary_search_by_key(&key, |entry| (entry.0, entry.1))",
         "        .ok()",
         "        .map(|index| &GLYPHS[index].2)",
         "}",
         ""]
out = Path(__file__).resolve().parents[1] / "crates/wqxemu/src/keypad/font.rs"
out.write_text("\n".join(rows), encoding="utf-8", newline="\n")
print(f"wrote {out}: {kept} glyphs, {total} alpha bytes")
